### ISSUE TITLE
Como emitir nota em contingência?

### ISSUE THREAD

**Issue by igorgbs** [TadaSoftware/PyNFe#108]
Gostaria de saber qual chamada devo fazer para emitir a nota em contingência.

**Comment by leogregianin** [comment]
@igorgbs,
 
Na emissão da nota, [como nesse exemplo](https://github.com/TadaSoftware/PyNFe/wiki/Emiss%C3%A3o-de-NFe), ao chamar a serialização em:

```python
serializador = SerializacaoXML(
    _fonte_dados,
    homologacao=homologacao,
    contingencia="Texto Justificativa da contingência"
) 
``` 
Passar a chave "contingencia" com o texto da justificativa.
 
No campo "nota_fiscal.forma_emissao" passar qual a forma da contingência, exemplos:

	2=Contingência FS-IA, com impressão do DANFE em formulário de segurança;
	3=Contingência SCAN (Sistema de Contingência do Ambiente Nacional);
	4=Contingência DPEC (Declaração Prévia da Emissão em Contingência);
	5=Contingência FS-DA, com impressão do DANFE em formulário de segurança;
	6=Contingência SVC-AN (SEFAZ Virtual de Contingência do AN);
	7=Contingência SVC-RS (SEFAZ Virtual de Contingência do RS);
	9=Contingência off-line da NFC-e (as demais opções de contingência são válidas também para a NFC-e).
	Para a NFC-e somente estão disponíveis e são válidas as opções de contingência 5 e 9.

Com isso, serão adicionadas automaticamente as tags dhCont e xJust exigidas na Contingência.

**Comment by leogregianin** [comment]
Precisamos voltar a discutir esse assunto.

(1) Existe um erro na serialização da contingência (pynfe/processamento/serializacao.py):
```python
if self._contingencia != None:
    etree.SubElement(ide, 'dhCont').text = nota_fiscal.data_emissao.strftime('%Y-%m-%dT%H:%M:%S') + tz # Data e Hora da entrada em contingência AAAA-MM-DDThh:mm:ssTZD
-   etree.SubElement(ide, 'xJust').text = nota_fiscal.self._contingencia  # Justificativa da entrada em contingência (min 20, max 256 caracteres)
+   etree.SubElement(ide, 'xJust').text = self._contingencia  # Justificativa da entrada em contingência (min 20, max 256 caracteres)
```

(2) e um problema na regra na definição da URL a enviar a contingência, ou seja, mesmo sendo um envio de contingência, a url continua sendo a mesma do webservice normal.

O que fiz para ajustar isso:

Em cada método, ou seja, ```autorizacao```, ```consulta_nota```, ```consulta_recibo```, ```status_servico``` e ```inutilizacao``` crio um novo parâmetro  ```contingencia=False```. Para que o método ```_get_url``` receba esse parâmetro ```contingencia=contingencia```.

Exemplos:

```python
def autorizacao(self, modelo, nota_fiscal, id_lote=1, ind_sinc=1, contingencia=False):
   (...)
   url = self._get_url(modelo=modelo, consulta='AUTORIZACAO', contingencia=contingencia)
   (...)

def consulta_nota(self, modelo, chave, contingencia=False):
   (...)
   url = self._get_url(modelo=modelo, consulta='CHAVE', contingencia=contingencia)
   (...)
```

No método ```_get_url``` verifico se é uma contingência e direciono a URL para Sefaz Virtual RS ou AN conforme a relação de webservices em contingência de cada UF do [Portal da NFe](http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=OUC/YVNWZfo=):

```python
    def _get_url(self, modelo, consulta, contingencia=False):
        """ Retorna a url para comunicação com o webservice """
        if contingencia:
            contingencia_svrs = ['AM', 'BA', 'CE', 'GO', 'MA', 'MS', 'MT', 'PE', 'PR']
            contingencia_svan = ['AC', 'AL', 'AP', 'DF', 'ES', 'MG', 'PA', 'PB', 'PI', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO']

            if self.uf.upper() in contingencia_svrs:
                if self._ambiente == 1:
                    ambiente = 'HTTPS'
                else:
                    ambiente = 'HOMOLOGACAO'
                if modelo == 'nfe':
                    # nfe Ex: https://nfe.fazenda.pr.gov.br/nfe/NFeStatusServico3
                    self.url = NFE['SVRS'][ambiente] + NFE['SVRS'][consulta]
                elif modelo == 'nfce':
                    # nfce Ex: https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeStatusServico3
                    self.url = NFCE['SVRS'][ambiente] + NFCE['SVRS'][consulta]
                else:
                    raise Exception('Modelo não encontrado! Defina modelo="nfe" ou "nfce"')
            elif self.uf.upper() in contingencia_svan:
                if self._ambiente == 1:
                    ambiente = 'HTTPS'
                else:
                    ambiente = 'HOMOLOGACAO'
                if modelo == 'nfe':
                    # nfe Ex: https://nfe.fazenda.pr.gov.br/nfe/NFeStatusServico3
                    self.url = NFE['SVAN'][ambiente] + NFE['SVAN'][consulta]
                elif modelo == 'nfce':
                    # nfce Ex: https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeStatusServico3
                    self.url = NFCE['SVRS'][ambiente] + NFCE['SVRS'][consulta]
                else:
                    raise Exception('Modelo não encontrado! Defina modelo="nfe" ou "nfce"')
            return self.url

        # estado que implementam webservices proprios
        lista = ['PR', 'MS', 'SP', 'AM', 'CE', 'BA', 'GO', 'MG', 'MT', 'PE', 'RS']
        if self.uf.upper() in lista:
            if self._ambiente == 1:
                ambiente = 'HTTPS'
```

Poderíamos reabrir essa issue?

**Comment by juniortada** [comment]
Vou reabrir
