### ISSUE TITLE
Manifestação do destinatário

### ISSUE THREAD

**Issue by luanrsiqueira** [TadaSoftware/PyNFe#115]
Bom dia, gostaria de esclarecer uma dúvida, eu realizo a ciência da nota , no entanto, não recebo essa nota posteriormente através da consulta por lote, e a nota já ta na sefaz, o que poderia ser esse problema?

**Comment by leogregianin** [comment]
Bom dia @luanrsiqueira,

Você também pode baixar a nota completa pelo número do NSU ou pela Chave de Acesso como demonstrado [aqui](https://github.com/TadaSoftware/PyNFe/wiki/Consulta-Distribui%C3%A7%C3%A3o).

Algumas UFs demoram até 48 horas para disponibilizar ao Ambiente Nacional de Distribuição DFe o XML após a ciência da operação.

Duas opções: espera a distribuição retornar o XML completo ou pega o XML diretamente com o fornecedor.

**Comment by luanrsiqueira** [comment]
Bom dia @leogregianin , 

Eu realizo a consulta por lote normalmente porém, quando vou realizar a ciência de novas notas,
somente retorna o resumo delas quando faço a consulta, tento manifestar novamente porém da duplicidade de evento. Estou realizando esses testes desde do início do mês.

**Comment by leogregianin** [comment]
Bom dia @luanrsiqueira, acredito que deve ter sido alguma instabilidade no webservice naquele momento. 
Utilizo [esse exemplo de código](https://github.com/TadaSoftware/PyNFe/wiki/Consulta-Distribuicao-1) para baixar as notas e estão sendo vindo corretamente.
