### ISSUE TITLE
Distribuição retornando 'Rejeicao: Falha no esquema xml'

### ISSUE THREAD

**Issue by gabzgg** [TadaSoftware/PyNFe#116]
Eu estou utilizando esse código pra buscar o xml de uma nota que já foi manifestada

```
con = ComunicacaoSefaz(uf, certificado, senha, homologacao)
xml = con.consulta_distribuicao(cnpj=CNPJ, chave=CHAVE)
```

com todos os parametros de certificado, senha e chave corretos, a homologação pra False
(a única coisa que eu não tenho muita certeza é a uf que eu estou utilizando, que é a 'pa', do meu estado mesmo)
e ele tem me retornado isso:

```
<retDistDFeInt versao="1.01">
<tpAmb>1</tpAmb>
<verAplic>1.3.9</verAplic>
<cStat>215</cStat>
<xMotivo>Rejeicao: Falha no esquema xml</xMotivo>
<dhResp>2021-07-29T17:04:08-03:00</dhResp>
<ultNSU>000000000000000</ultNSU>
<maxNSU>000000000000000</maxNSU>
</retDistDFeInt>

```
como ele pode dar erro no schema? eu tenho que indicar algum schema em algum lugar? o que eu estou fazendo de errado?

**Comment by leogregianin** [comment]
Bom dia @gabzgg,

Rejeição de schema pode ser os dados passados nas variáveis CNPJ e/ou CHAVE.

CNPJ tem que ter tamanho de 14 dígitos, a chave de acesso tem que ter 44 dígitos e ambos devem ser preenchidos sem máscara de formatação, ou seja, sem traços ou pontos e sem espaços no início ou no final do valor.
