### ISSUE TITLE
Informação do identificador do CSRT e do Hash do CSRT

### ISSUE THREAD

**Issue by leogregianin** [TadaSoftware/PyNFe#119]
Em testes de NFe/NFCe no ambiente de homologação do Paraná ocorre a rejeição 975.
Seria interessante já implementar esses dois campos para uma futura validação da regra para o Paraná e para as demais UFs em ambiente de produção.

```xml
<protNFe versao='4.00'>
 <infProt>
  <tpAmb>2</tpAmb>
  <verAplic>PR-v4_7_33</verAplic>
  <chNFe>412108XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</chNFe>
  <dhRecbto>2021-08-04T12:04:06-03:00</dhRecbto>
  <digVal>O3CztXXXXXXXXXXXXOx/BRqLus=</digVal>
  <cStat>975</cStat>
  <xMotivo>Obrigatoria a informacao do identificador do CSRT e do Hash do CSRT</xMotivo>
 </infProt>
</protNFe>```

**Comment by juniortada** [comment]
Isso foi causado por um erro da SEFAZ PR que adicionou esta validação antes do tempo.
