### ISSUE TITLE
Possiveis valores para indicador_ie

### ISSUE THREAD

**Issue by ftbarata** [TadaSoftware/PyNFe#125]
Boa noite, alguem sabe os possíveis valores para o indicador_ie ?

Só tem assim na documentação:

indicador_ie=9,  # 9=Não contribuinte

E se for contribuinte?

**Comment by juniortada** [comment]
Boa noite @ftbarata
1=Contribuinte ICMS (informar a IE do destinatário);
2=Contribuinte isento de Inscrição no cadastro de
Contribuintes
9=Não Contribuinte, que pode ou não possuir Inscrição
Estadual no Cadastro de Contribuintes do ICMS.
Nota 1: No caso de NFC-e informar indIEDest=9 e não
informar a tag IE do destinatário;
Nota 2: No caso de operação com o Exterior informar
indIEDest=9 e não informar a tag IE do destinatário;
Nota 3: No caso de Contribuinte Isento de Inscrição
(indIEDest=2), não informar a tag IE do destinatário.

https://github.com/TadaSoftware/PyNFe/blob/master/pynfe/processamento/serializacao.py#L154

https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=J%20I%20v4eN00E=
