### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by rethRed** [TadaSoftware/PyNFe#127]
boa tarde, Estou usando a biblioteca, mas  esta aparecendo um erro de atributo.

 det = self._serializar_produto_servico(item, modelo=nota_fiscal.modelo, retorna_string=False)
  File "C:\Users\\AppData\Roaming\Python\Python39\site-packages\pynfe\processamento\serializacao.py", line 512, in _serializar_produto_servico
    if produto_servico.inf_adicionais_produto:
AttributeError: 'NotaFiscalProduto' object has no attribute 'inf_adicionais_produto'

olhei no código fonte e eu não encontrei o "inf_adicionais_produto".

**Comment by juniortada** [comment]
Boa tarde @rethRed, me parece que você está tentando usar incorretamente a lib.
Métodos privado (que iniciam com _ ) não devem ser invocados da forma como você está fazendo.
Instancie os objetos e utilize somente os métodos públicos. 
Recomendo que você leia a documentação do projeto.

https://github.com/TadaSoftware/PyNFe/wiki

Aqui está informações adicionais do produto:

https://github.com/TadaSoftware/PyNFe/blob/master/pynfe/processamento/serializacao.py#L511

Que caso deseja que seja informado seria da seguinte foram:

```python
from pynfe.entidades.notafiscal import NotaFiscal

nota_fiscal = NotaFical(
  code
)

nota_fiscal.adicionar_produto_servico(
  inf_adicionais_produto = 'bla bla bla'
)
```
