### ISSUE TITLE
Não encontro nada sobre algumas informações técnicas

### ISSUE THREAD

**Issue by developerAdriano** [TadaSoftware/PyNFe#128]
Como faço para finalizar o campos que não tem nenhuma orientação ? Por exemplo eu não entendi como a api aceita calcular os tributos, tem alguns valores default mas estou muito duvidoso de deixa-los como está, estou pesquisando a dias mas não encontro nada sobre nfe em relação aos campos de orientação! Alguém pode me ajudar por favor

**Comment by leogregianin** [comment]
@developerAdriano Bom dia,

Eu recomendo deixar o preenchimento dos campos para responsabilidade da empresa que irá emitir a nota.

Você pode até informar o valor padrão para usuário, mas deixar a responsabilidade para ele confirmar.

Isso porque cada empresa pode informar os tributos de forma diferente, cada empresa tem um regime tributário diferente, cada estado da federação tem suas regras próprias e cada contabilidade tem sua interpretação própria.

**Comment by juniortada** [comment]
@developerAdriano Boa noite!
Quais informações mais especificamente? Valor dos tributos aproximado?
Se for isso, eu recomendo utilizar o IBPT ou alguma lib/api que usa a base deles.
Ex:

https://github.com/base4sistemas/ibptws

https://ibpt.com.br/

**Comment by developerAdriano** [comment]
@juniortada Boa noite ! Ajudou muito, fiquei em dúvida se teria que passar o valor calculado, mas tenho que passar propriedades de a cordo com a empresa! Muito obrigado
