### ISSUE TITLE
403 - Forbidden: Access is denied, testando status_servico('nfe') - SP

### ISSUE THREAD

**Issue by crsilveira** [TadaSoftware/PyNFe#132]
<h2>403 - Forbidden: Access is denied.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>

Faço testes com diversos UFs , e não tenho problema, agora com SP , dá o erro acima, alguém teve este problema ?

**Comment by leogregianin** [comment]
@crsilveira, por aqui está tudo normal.

Peguei os envelopes de envio e retorno:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
	<soap:Body>
		<nfeDadosMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4">
			<consStatServ versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe">
				<tpAmb>1</tpAmb>
				<cUF>35</cUF>
				<xServ>STATUS</xServ>
			</consStatServ>
		</nfeDadosMsg>
	</soap:Body>
</soap:Envelope>
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<soap:Body>
		<nfeResultMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4">
			<retConsStatServ versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe">
				<tpAmb>1</tpAmb>
				<verAplic>SP_NFE_PL009_V4</verAplic>
				<cStat>107</cStat>
				<xMotivo>Serviço em Operação</xMotivo>
				<cUF>35</cUF>
				<dhRecbto>2021-12-30T10:18:41-03:00</dhRecbto>
				<tMed>1</tMed>
			</retConsStatServ>
		</nfeResultMsg>
	</soap:Body>
</soap:Envelope>
```

Consegue debugar para ver se realmente foi direcionado para a [URL de SP](https://nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx)?

**Comment by crsilveira** [comment]
Exception: Falha ao carregar certificado digital A1. Verifique a senha do certificado>>>
 uf  'sp'
>>> url                                                                                                            
'https://homologacao.nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx'
>>> VERSAO_PADRAO                                                                                                  
'4.00'                                                                                                             
>>> self._ambiente                                                                                                 
2

<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
  <soap:Body>
    <nfeDadosMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4">
      <consStatServ versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe">
        <tpAmb>2</tpAmb>
        <cUF>35</cUF>
        <xServ>STATUS</xServ>
      </consStatServ>
    </nfeDadosMsg>
  </soap:Body>
</soap:Envelope>

urllib3/connectionpool.py:842: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>403 - Forbidden: Access is denied.</title>
<style type="text/css"> ......

parece idêntico .....  vc está no estado de São Paulo ?

**Comment by crsilveira** [comment]
from pynfe.processamento.comunicacao import ComunicacaoSefaz

certificado = "/home/publico/tmp/cert.pfx"
senha = 'aaabbb'
uf = 'sp'
homologacao = True


con = ComunicacaoSefaz(uf, certificado, senha, homologacao)
xml = con.status_servico('nfe')
print (xml.text)

estou executando este código.

**Comment by leogregianin** [comment]
> parece idêntico ..... vc está no estado de São Paulo ?

A única diferença é que fiz o teste em ambiente de produção com certificado digital de São Paulo, como você pode ver nas tags tpAmb=1 e cUF=35.

**Comment by crsilveira** [comment]
Estou usando python 3.9.5 ,  acredito q deva ser alguma lib ... já mudei várias mas sem sucesso.

**Comment by crsilveira** [comment]
RESOLVIDO, o problema era o certificado mesmo, parecia tudo certo, não estava vencido , estava correto, mas peguei outro certificado , e passou sem problema, obrigado.
