### ISSUE TITLE
Sefaz Ceará - (CE) Serviços migrados para Sefaz Virtual Rio Grande do Sul (SVRS). Vide URLs SVRS.

### ISSUE THREAD

**Issue by leandrosouzaxd** [TadaSoftware/PyNFe#153]
Erro Atual ao consulta cadastro  :

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0400A7D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
During handling of the above exception, another exception occurred:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nfe-homologacao.https', port=443): Max retries exceeded with url: //cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro4.asmx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0400A7D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Correção:
Adicionar no arquivo comunicacao.py na linha 210 no array lista_svrs o valor  'CE'

lista_svrs = ['AC', 'RN', 'PB', 'SC', 'PA', 'CE']

**Comment by juniortada** [comment]
https://www.sefaz.ce.gov.br/2021/12/08/comunicado-nfe-migracao-para-svrs/
