### ISSUE TITLE
Duvida de funcionamento

### ISSUE THREAD

**Issue by Weslei25** [TadaSoftware/PyNFe#159]
Bom dia pessoal!

Estou pensando em usar o PyNFe em um projeto já existente, e gostaria de saber se existe custos pra isso, ou se é open source free.

Gostaria também de entender como implantar no projeto, tenho conhecimento de como funciona esse processo da sefaz mas o PyNfe é novo pra min, obrigado pela ajuda.

**Comment by juniortada** [comment]
Bom dia @Weslei25 !
O PyNFe usa licença open source LGPL 
https://github.com/TadaSoftware/PyNFe/blob/master/LICENSE

Você pode tirar suas dúvidas sobre como utilizar a biblioteca na wiki
https://github.com/TadaSoftware/PyNFe/wiki

Ou no fórum de discussões
https://github.com/TadaSoftware/PyNFe/discussions
https://groups.google.com/g/pynfe
