### ISSUE TITLE
Consumo indevido

### ISSUE THREAD

**Issue by Weslei25** [TadaSoftware/PyNFe#160]
Olá pessoal obtive resposta de consumo indevido vocês podem me ajudar a tratar esse bloqueio?
![image](https://user-images.githubusercontent.com/76075516/152525823-8f027f4e-0815-4a38-afa3-4ac2a28c7944.png)

**Comment by juniortada** [comment]
Bom dia @Weslei25! 
A resposta está na sua imagem: "Consumo Indevido. **[Consulte NT 2018.002 v1.00]**
Você está quebrando alguma regra de consumo da SEFAZ PR
link das NT (baixe a 2018.002 para entender melhor)
https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=04BIflQt1aY=
Aqui um resumo:
https://blog.tecnospeed.com.br/nota-tecnica-2018-002-da-nf-e-e-nfc-e-consumo-indevido/
