### ISSUE TITLE
Danfe

### ISSUE THREAD

**Issue by Weslei25** [TadaSoftware/PyNFe#163]
Bom dia pessoal!

Para imprimir a danf eu preciso escrever o código ou já existe esse código no pynfe?
Desde já agradeço a resposta!

![Screenshot_4](https://user-images.githubusercontent.com/76075516/152997105-979c120f-5038-4861-9c86-2e2b1b8d288e.png)

**Comment by juniortada** [comment]
Boa noite @Weslei25 
O Danfe depende mais do tipo da sua aplicação (web/desktop/api/etc)
Com o xml assinado e autorizado pode usar qualquer lib para gerar o DANFE
Aqui nestes comentários tem links e dicas para gerar seu próprio DANFE de acordo com o seu projeto.

https://github.com/TadaSoftware/PyNFe/issues/8
https://groups.google.com/g/pynfe/c/_YPPG0jg3oA
