### ISSUE TITLE
Emitir NFC-e em SC qrCode inválido

### ISSUE THREAD

**Issue by FernandoBernardi** [TadaSoftware/PyNFe#193]
**225 -  Rejeicao: Falha no Schema XML da NFe (Elemento: enviNFe/NFe[1]/infNFeSupl/qrCode/)**

Encontrei dois problemas ao emitir nfce em sc, e consegui resolver alterando o source de serializacao e webservices do PyNFe:

- Primeiro: Está montando a url da tag **qrCode** com dois "p" exemplo = "/nfce/consulta?p=p=" , pois no webservice URL de SC já tem um p= informado e acaba ficando duplicado.
- Segundo: Em **SerializacaoQrcode -> thfe** não está fazendo o replace de caracteres especiais (&lt; &gt;, ... )

**Comment by leogregianin** [comment]
@FernandoBernardi que bom que conseguiu resolver e utilizar a lib.
Poderia fazer um `pull request` com as alterações que fez para melhorar o projeto?

**Comment by jprpessoa** [comment]
Acredito que eu esteja enfrentando o mesmo problema, seria muito bem vinda a solução. 

Schema XML: The 'http://www.portalfiscal.inf.br/nfe:qrCode' element is invalid - The value '' is invalid according to its datatype 'String' - The Pattern constraint failed.
Caminho: NFe[1]/infNFeSupl/qrCode/

225 - Rejeicao: Falha no Schema XML da NFe (Elemento: enviNFe/NFe[1]/infNFeSupl/qrCode/)

**Comment by juniortada** [comment]
https://github.com/TadaSoftware/PyNFe/pull/198
