### ISSUE TITLE
Duvida NfeConsultaCadastro 'TO'

### ISSUE THREAD

**Issue by leandrosouzaxd** [TadaSoftware/PyNFe#197]
Bom dia, não encontrei o metodo de consulta de cadastro de TO.
Não esta implementado ?

**Comment by leogregianin** [comment]
@leandrosouzaxd, a relação de quais UFs utilizam determinados webservices está aqui: 
https://www.nfe.fazenda.gov.br/portal/webServices.aspx

`Tocantins` utiliza os serviços da `Sefaz Virtual do RS` mas não para consultas de cadastros.

**Comment by leandrosouzaxd** [comment]
Entendi, nesse caso empresas de Tocantins não utilizam essa parte de consulta, nesse caso seria sintegra pra obter o status de uma empresa ?
Pode encerrar a issue, agradeço demais a disposição!
