### ISSUE TITLE
Monitorar nota emitida para meu CNPJ

### ISSUE THREAD

**Issue by hermesalvesbr** [TadaSoftware/PyNFe#206]
Boa tarde pessoal,

Poderiam me indicar alguma lib/sdk que permita via meu certificado digital que eu monitore as notas fiscais emitidas para o meu CNPJ?

Gostaria de saber quando alguém emitir uma nota fiscal de venda para o meu cnpj. 

Pode ser em outra linguagem, não tem problemas. 

Agradeço desde já qualquer contribuição,

**Comment by leogregianin** [comment]
Nesse projeto, PyNFe, temos esses caminhos:
  * https://github.com/TadaSoftware/PyNFe/wiki/Consulta-Distribui%C3%A7%C3%A3o
  * https://github.com/TadaSoftware/PyNFe/wiki/Fluxo-da-Consulta-de-Distribuicao

Veja se lhe atende.

Essa issue poderia ser movida para a seção de [discussions](https://github.com/TadaSoftware/PyNFe/discussions).

@hermesalvesbr sugiro ler a documentação dos projetos antes de abrir issues em dezenas de projetos esperando algo pronto.

**Comment by hermesalvesbr** [comment]
Obrigado, postei muito pois , graças a você que descobri que se chama consulta de distribuição. Eu não tinha um norte. Muito obrigado.
