### ISSUE TITLE
Consumo indevido

### ISSUE THREAD

**Issue by Weslei25** [TadaSoftware/PyNFe#224]
O consumo indevido "Rejeição 656" é um erro muito incomodo, e a solução proposta pela SEFAZ não funciona pois hoje em dia a quase todas as soluções dentro do TI de uma empresa contem o modulo de rastrio de notas.

Seria possivel desenvolvermos algo pra evitar esse problema?

Informação: https://blog.tecnospeed.com.br/consumo-indevido-como-resolver/#:~:text=A%20Rejei%C3%A7%C3%A3o%20(656)%3A%20Consumo,a%20Sefaz%20sem%20real%20necessidade.

**Comment by leogregianin** [comment]
@Weslei25 não entendi seu problema. 
É só seguir as orientações das Notas Técnicas e implementar os controles de consumo no seu código.

**Comment by Uriel-Alves** [comment]
Infelizmente, por alguns erros seguidos, também recebi o bloqueio :smile: 

@leogregianin , a rejeição 656 foi uma [nota técnica publicada na Sefaz](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=HAYP6dvLy7I=), como solução para alguns "problemas técnicos" que foram enfrentados.

A norma está bloqueando por 60 minutos, quando estes pontos são alcançados:
- Uma NF-e ou NFC-e for enviada mais de 30 vezes e apresentar a mesma rejeição
- Um evento apresentar 20 vezes a mesma rejeição
- Uma Inutilização for enviada mais de 20 vezes e apresentar a mesma rejeição
- Uma NF-e for consultada mais de 10 vezes em 1 hora
- Um Recibo for consultado mais de 40 vezes em 1 hora

Acredito que, uma solução para isto seria gravar e analisar histórico de payloads enviados aos WebServices, gerando exceções antes de cairmos em um bloqueio.

**Comment by leogregianin** [comment]
@Uriel-Alves sim, estou ciente da nota técnica, porém é a aplicação cliente que deve tratar isso e não a lib PyNFe.
