### ISSUE TITLE
notas de saida

### ISSUE THREAD

**Issue by diogoheck6** [TadaSoftware/PyNFe#230]
Bom dia!
além de emitir notas contra o CNPJ (fornecedores), é possivel adaptar o programa (mudar algum arguemnto) para que ele traga também as notas que o cliente emitiu? Eu sei que o cliente deve armazenar as notas de saidas, mas esse processo seria a titulo de cruzar informações, fazer outros processos e não para guardar o xml, mas sim aproveitar para tirar alguma informação. Muito Obrigado

**Comment by diogoheck6** [comment]
eu to tentando fazer um "app" pro estado do RS (no proprio site do Sefaz RS eles disponibilizam as notas tecnicas e permitem que se baixa tanto xml de entrada, quanto saida, tando de NFE, NFCe e CTe.....mas não sei se o app de vcs com adapatação tambem faria isso e qual adaptação teria q ser feita....eu conheço um pouco de python ja mas nunca trabalhei com webservice, não sei nem por onde começar para fazer as requisições soap...ja pesquisei to parado.....não sei se sabem de algum lugar que ensine, dê um norte sobre o assunto.....

**Comment by juniortada** [comment]
@diogoheck6 SEFAZ RS tem alguns métodos que não são do padrão nacional e não estão implementados em outros webservices, como por exemplo download de NF-e para contabilista responsável. 
Fora isso você pode habilitar um CPF/CNPJ habilitado a baixar o xml dessa nota através de certificado digital
preenchendo este campo na hora de emitir a NF-e.
https://github.com/TadaSoftware/PyNFe/blob/d2b0fe7e4a59cfcf508552356e1a4a5bac531cfe/pynfe/processamento/serializacao.py#L233
https://github.com/TadaSoftware/PyNFe/wiki/Emiss%C3%A3o-de-NFe#:~:text=%23%20exemplo%20de%20grupo%20de%20pessoas%20autorizadas%20a%20baixar%20xml
