### ISSUE TITLE
NFS-E ABRASF NACIONAL - ISSNET (DF)

### ISSUE THREAD

**Issue by tiagocardosos** [TadaSoftware/PyNFe#235]
Pessoal, no próximo dia 01/11, os contribuintes prestadores de serviços, deixarão de utilizar a NF-e (DANFE, NFC-E, E NOTA CONJUGADA) e passarão a utilizar a NFS-E ABRASF NACIONAL.

Vi que o projeto já atendendo os autorizadores Ginfes e Betha. Está nos planos de alguém fazer essa implementação?

[NFS-e_Manual_de_Orientacao_do_Contribuinte_2.04.pdf](https://github.com/TadaSoftware/PyNFe/files/9843441/NFS-e_Manual_de_Orientacao_do_Contribuinte_2.04.pdf)

[PRINCIPAIS MUDANÇAS DF - ISS.pdf](https://github.com/TadaSoftware/PyNFe/files/9843442/PRINCIPAIS.MUDANCAS.DF.-.ISS.pdf)

**Comment by juniortada** [comment]
@tiagocardosos as integrações com NFS-e estão bem desatualizadas e tem um bom tempo que não recebem 
nenhuma tipo de atualizações.
