### ISSUE TITLE
Rejeição Falha no schema (cod215) - consulta_nota

### ISSUE THREAD

**Issue by Uriel-Alves** [TadaSoftware/PyNFe#237]
Olá, gostaria primeiramente de agradecer pelo trabalho aqui feito, esta lib é excelente!

Com o código:
```python
    con = ComunicacaoSefaz('sp', certificado, senha, True)
    nfe = '4031864SKLNIFJSI4ZJCIXXFO8HIXXXX'
    xml = con.consulta_nota('nfe', nfe)
    print('NFE\n\n',xml, '\n\n',xml.content)
```

Amigos, estou recebendo um retorno 200, porém com erro:
```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<soap:Body>
<nfeResultMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4"><retConsSitNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe">
<tpAmb>2</tpAmb>
<verAplic>SP_NFE_PL009_V4</verAplic>
<cStat>215</cStat>
<xMotivo>Rejei\xc3\xa7\xc3\xa3o: Falha no schema XML</xMotivo>
<cUF>35</cUF>
<dhRecbto>0001-01-01T00:00:00+00:00</dhRecbto><chNFe>4031864SKLNIFJSI4ZJCIXXFO8HIXXXX</chNFe></retConsSitNFe></nfeResultMsg></soap:Body></soap:Envelope>
```

Alguém saberia o motivo desta causa? Pesquisando no manual de integração, só informa para checar o schema XML e nada mais...

Desde já, agradeço a atenção de vocês! Valeu

**Comment by Uriel-Alves** [comment]
Observando os exemplos postados no manual de integração SEFAZ (file:///home/uriel/Documents/sefaz/Manual_Integracao_Contribuinte_4.01-NT2009.006.pdf) [página 15]

Vi que, o elemento soap está escrito com a versão 12. (soap12)
```xml
<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
 <soap12:Header>
 <nfeCabecMsg xmlns="http://www.portalfiscal.inf.br/sce/wsdl/NfeRecepcao2">
 <versaoDados>string</versaoDados>
 </nfeCabecMsg>
 </soap12:Header>
 <soap12:Body>
 <nfeRecepcao xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2">
 <nfeDadosMsg>xml</nfeDadosMsg>
 </nfeRecepcao>
</soap12:Body>
</soap12:Envelope>
```

Nos processamentos de comunicação Sefaz (ComunicacaoSefaz), temos os xml sendo montado com `soap`, ao inves de `soap12`

Então, eu inseri ~~uma guambiarra~~ com replace, **da linha 513 à 516** no arquivo `comunicacao.py`:
```python
#...
xml = xml_declaration + xml
xml = xml.replace('soap:', 'soap12:')
xml = xml.replace(':soap', ':soap12')
# Faz o request com o servidor
result = requests.post(url, xml, headers=self._post_header(), cert=chave_cert, verify=False)
#...
```

Provavelmente temos o lugar correto para aplicar essa alteração, mas foi para fins de testes apenas (tentando igualar o request com o exemplo do manual).

Porém, agora estou tomando 656 (Consumo indevido) por repetir o erro muitas vezes e não consegui verificar se o problema foi corrigido... :disappointed: 

Quando eu sair do bloqueio eu posto atualizalções por aqui. Valeeeu

**Comment by Uriel-Alves** [comment]
Infelizmente o erro persiste com o mesmo código de rejeito 215 ( falha no schema XML ).

**Comment by juniortada** [comment]
@Uriel-Alves você mascarou os dados apenas para postar aqui ou enviou a chave de nfe assim:
`nfe = '4031864SKLNIFJSI4ZJCIXXFO8HIXXXX'`
Se foi isso o erro é este, pois o layout só aceita números.

**Comment by Uriel-Alves** [comment]
@juniortada , eu testei utilizando esse formato sim, vindo de uma emissão via MEI.
Porém, tentei também, utilizando notas no padrão numérico:
_8233738269201941718420230425042023660000_

Removendo quaisquer alterações que fiz na lib.
Mesmo assim, recebo o mesmo erro:
_215, Rejeicao: Falha no schema XML_

Seguem request e response, respectivamente:

```xml
<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Body><nfeDadosMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4"><consSitNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><xServ>CONSULTAR</xServ><chNFe>8233738269201941718420230425042023660000</chNFe></consSitNFe></nfeDadosMsg></soap:Body></soap:Envelope>
```

```xml
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><nfeResultMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4"><retConsSitNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>SVRS202209051212</verAplic><cStat>215</cStat><xMotivo>Rejeicao: Falha no schema XML</xMotivo><dhRecbto>2022-10-31T09:21:00-03:00</dhRecbto></retConsSitNFe></nfeResultMsg></soap:Body></soap:Envelope>
```

Vale lembrar que estou utilizando chaves reais de notas. Como também, um certificado AI assinado na ICP Brasil.
Testei em ambos ambientes, e me deu o mesmo resultado.
Para realizar os testes, estou utilizando Python 3.7.1, no debian 10.

**Comment by juniortada** [comment]
@Uriel-Alves você continua com o mesmo erro, essa chave de nota que você está informando não possui 44 caracteres.
Valide a chave da nota antes de enviar, precisa conter 44 caracteres dígitos numéricos.

**Comment by leogregianin** [comment]
Bom dia,
Essa chave de acesso: 8233738269201941718420230425042023660000 ainda está no padrão errado.
Além de ser numérica, ela deve ter `sempre` 44 dígitos. Nesse site tem o detalhamento de como compõe a chave de acesso: https://www.oobj.com.br/bc/article/como-%C3%A9-formada-a-chave-de-acesso-de-uma-nf-e-nfc-e-de-um-ct-e-e-um-mdf-e-281.html
Tem certeza que está usando NFe?

**Comment by Uriel-Alves** [comment]
Ok. O erro é o tipo da nota! 
Estava passando chaves `NFSe` e tentando consulta-las como `NFe`. :facepalm: :facepalm: 

Isso explica a rejeição XML, visto que é um outro tipo de nota a ser consultada.

Valeu gente! Irei agora tentar a comunicação novamente utilizando a classe _ComunicacaoNfse_
Muitissimo obrigado pelo suporte!! 
Até a próxima
