### ISSUE TITLE
Assinatura inválida

### ISSUE THREAD

**Issue by vozdatela** [TadaSoftware/PyNFe#242]
Olá!

Encontrei esse projeto e achei interessante. Estou tentando criar um emissor de nota com ele.
De cara, estou empacado com a assinatura inválida que não consigo resolver.

Estou usando o exemplo 'Emitir NFe' do próprio 'wiki do PyNFe!' para aprovar uma nota em ambiente de homologação.

Apenas modifiquei os dados do emitente e do cliente.
Já fiz toda a verificação e não há caracteres especiais ou espaços em branco nos dados do emitente e do cliente. O restante das informações, como dito, segue o modelo do PyNFe.

Retorno:
Falha no reconhecimento da autoria ou integridade do arquivo digital.

Analisando o xml no validador da https://www.sefaz.rs.gov.br/nfe/NFE-VAL.aspx:
 Assinatura Digital: Inválida
    Regras de Negócio [Ambiente de Homologação (Testes)] 1 erro de validação
    297 - [Simulacao] Rejeicao: Assinatura difere do calculado

Por favor, como posso corrigir isso?
O projeto PyNFe foi descontinuado? olhando o grupo havia mensagens muito antigas a respeito dele.

Obrigado.
Geovani.

**Comment by FernandoBernardi** [comment]
Olá encontrei o mesmo problema, resolvi alterando as versões no requirements assim:

pyopenssl==22.1.0
signxml==2.9.0

O que acontece é que a ultima versão do signxml não está compatível com o projeto e como não ficou travado a versão ele está pegando a ultima versão quando instala pela primeira vez.

Espero ter ajudado.

**Comment by vozdatela** [comment]
Isso mesmo Fernando. Funcionou! 

Como apenas comecei. Na primeira vez que envio, aprova e dá erro no retorno. Da segunda vez, vem a informação de 'duplicidade'. Então, sei que deu certo. Como até agora eu só recebia o erro de assinatura inválida, só criei o tratamento pra ele. Vou seguir aqui, graças à sua ajuda! Obrigado mesmo!

**Comment by vozdatela** [comment]
Fernando, sem querer abusar da sua boa vontade, não encontrei nada sobre a impressão da nota, o danfe, na documentação.
Não existe?

**Comment by mvellasco** [comment]
Olá Geovani,

Entrando aqui na discussão porque tive um problema similar, com a impressão
da danfe(não suportada pela biblioteca), e consegui resolver utilizando
essa biblioteca do ERPBrasil https://github.com/erpbrasil/erpbrasil.edoc.pdf
. É bem simples de usar, e funciona muito bem.


Miguel Oliveira Vellasco
Programador de Computadores / Computer Programmer

(PT) Esta mensagem contém informação confidencial ou privilegiada, sendo
seu sigilo protegido por lei. Se você não for o destinatário ou a pessoa
autorizada a receber esta mensagem, não pode usar, copiar ou divulgar as
informações nela contidas ou tomar qualquer ação baseada nessas
informações. Se você recebeu esta mensagem por engano, por favor, avise
imediatamente ao remetente, respondendo o e-mail e em seguida
apague-a. Agradecemos sua cooperação.

(EN) This message contains confidential or privileged information and its
confidentiality is protected by law. If you are not the addressed or
authorized person to receive this message, you must not use, copy, disclose
or take any action based on it or any information herein. If you have
received this message by mistake, please advise the sender immediately by
replying to the e-mail and then delete it. Thank you for your cooperation.




Em qui., 17 de nov. de 2022 às 15:18, Geovani ***@***.***>
escreveu:

**Comment by vozdatela** [comment]
Valeu, Miguel!

**Comment by vozdatela** [comment]
Miguel, não consigo instalar:
pip install erpbrasil.edoc.pdf
        ModuleNotFoundError: No module named 'fcntl'
Pesquisei e vi que o 'fcntl' não está disponível no Windows.

Li na documentação a parte da linha de comando pro windows:
    set PYTEST_ADDOPTS=--cov-append tox
    
Mas não deu resultado. Achei a documentação muito confusa. Diferente do que estou acostumado a ver. Se puder me ajudar com isso, agradeço.

**Comment by mvellasco** [comment]
Geovani, essa biblioteca depende do LibreOffice e de pacotes/bibliotecas
que fazem a interação com ele. Eu acredito que esses só estão disponíveis
em ambientes Linux, na minha imagem do docker eu utilizo o debian slim
buster. Sobre a documentação é um pouco confusa mesmo, mas você só vai
precisar chamar um método para gerar o pdf.

from erpbrasil.edoc.pdf import base

return base.ImprimirXml.imprimir(string_xml=xml_output, output_dir='.')


Miguel Oliveira Vellasco
Programador de Computadores / Computer Programmer

(PT) Esta mensagem contém informação confidencial ou privilegiada, sendo
seu sigilo protegido por lei. Se você não for o destinatário ou a pessoa
autorizada a receber esta mensagem, não pode usar, copiar ou divulgar as
informações nela contidas ou tomar qualquer ação baseada nessas
informações. Se você recebeu esta mensagem por engano, por favor, avise
imediatamente ao remetente, respondendo o e-mail e em seguida
apague-a. Agradecemos sua cooperação.

(EN) This message contains confidential or privileged information and its
confidentiality is protected by law. If you are not the addressed or
authorized person to receive this message, you must not use, copy, disclose
or take any action based on it or any information herein. If you have
received this message by mistake, please advise the sender immediately by
replying to the e-mail and then delete it. Thank you for your cooperation.




Em qui., 17 de nov. de 2022 às 16:43, Geovani ***@***.***>
escreveu:

**Comment by vozdatela** [comment]
Olá novamente, Miguel.

Consegui algum progresso com sua dica. Obrigado.
No entanto, estou novamente travado em outro ponto.

Como sugerido, importei apenas o base e isso funcionou.
Minha dificuldade está na parte da renderização do arquivo:

def _renderiza_documento
   t = Template(arq_template.name, arq_odt.name)
    
PermissionError: [Errno 13] Permission denied: 'g:\\tempo\\tmpc7k5oiye'

Pesquisando a respeito, encontrei orienteação para alterar a pasta ou mesmo o disco de destino. Não adiantou, como se pode ver pela mensagem.

Também li que o erro é porque o arquivo se encontra aberto.
Ok. fechei os arquivos: arq_template.close() arq_odt.close()

Mas se fechar os arquivos, eles deixam de existir na pasta.

Alguma sugestão?
