### ISSUE TITLE
maxNSU = 0 no consulta_distribuição. Nenhum documento localizado

### ISSUE THREAD

**Issue by RodrigoCardoso08** [TadaSoftware/PyNFe#256]
Estou utilizando o método consulta_distribuição da classe ComunicacaoSefaz da seguinte forma:
xml = con.consulta_distribuicao(cnpj=CPFCNPJ, chave=CHAVE, nsu=NSU)
onde CHAVE= None e NSU = 0.
 Com isso, eu esperava receber uma lista dos XMLs das notas fiscais emitidas nos últimos 15 dias para o CNPJ que eu informei. No entanto, eu recebo a resposta "Nenhum documento localizado", cStat = 137 e maxNSU = 0
 Gostaria de saber se eu é quem estou fazendo a requisição de maneira errada ou se é alguma instabilidade da SEFAZ. Você sabe me responder?
OBS1: Eu tenho o certificado digital do destinatário da nota fiscal. 
OBS2: Utilizando esse mesmo método e passando o valor da chave de uma nota fiscal existente eu consigo obter todo o XML da NF-e tal como esperado. Ou seja, o problema é na consulta por NSU.
OBS3: Entrando no portal da Fazenda eu consigo concluir que existem sim notas fiscais a serem apresentadas.

Desde já agradeço pela atenção!

**Comment by RodrigoCardoso08** [comment]
@ibemoreira eu acredito que já existam notas com "Ciência da Operação" no ambiente do governo,  pois abrindo o próprio portal da fazenda pelo browser é possível ver várias notas manifestadas com ciência. Isso por si só já não basta?

**Comment by leogregianin** [comment]
> @ibemoreira eu acredito que já existam notas com "Ciência da Operação" no ambiente do governo, pois abrindo o próprio portal da fazenda pelo browser é possível ver várias notas manifestadas com ciência. Isso por si só já não basta?

Somente esse critério não basta. Existem inúmeras regras e, nas últimas atualizações, adicionaram vários outras restrições, por exemplo:

* Se o certificado digital CNPJ não utiliza os serviços de DistribuicaoDFe a mais de 30 dias, os serviços serão suspensos para esse CNPJ até a próxima consulta, com isso, ativa novamente a sequencia de NSU para aquele certificado consultado.

* Se não existir mais documentos a serem retornados (cStat=137) o usuário deve aguardar uma hora para realizar nova consulta. A realização de novas consultas em 1h, após receber a mensagem cStat137, gerará o uso indevido, retornando cStat=656. Nesse caso, o CNPJ é bloqueado por 1 hora, sendo impedido de realizar novas consultas nesse intervalo. Decorrido o intervalo de tempo, o desbloqueio será automático. 

* O usuário deve sempre realizar a consulta baseada no ultNSU retornado na consulta anterior. Se consultar fora da sequência, será bloqueado. com a mensagem: "Rejeição: Consumo Indevido. Deve ser utilizado o ultNSU nas solicitações subsequentes. Tente após 1 hora"

* Se diversas aplicações do mesmo CNPJ efetuarem consultas por NSU devem seguir a mesma sequência de numeração ordenada e de forma ascendente, caso contrário, ocorre rejeição de Consumo Indevido. 

* Será permitido um número limitado de consultas por chave de acesso ou NSU em um período de 1 hora. Se o usuário continuar consultando após atingir o limite de consultas por chave de acesso ou NSU em 1 h, retornará a mensagem 656 - Consumo indevido - ultrapassou o limite de 20 consultas por hora. Nesse caso, o CNPJ é bloqueado por 1 hora.

* Em quaisquer tipos de consulta, quando o usuário receber a mensagem 656 - consumo indevido, deve aguardar 1 hora. Se retomar a consulta antes de completar 1 (uma) hora, o tempo é zerado e a contagem reiniciará até completar 1 hora.
