### ISSUE TITLE
Erro no método consulta_distribuicao

### ISSUE THREAD

**Issue by homerokzam** [TadaSoftware/PyNFe#271]
Esta consulta:
xml = con.consulta_distribuicao(cnpj=CNPJ, chave=CHAVE, nsu=ULT_NSU, consulta_nsu_especifico=False)
print(xml.text)

Está gerando o erro:
TypeError: ComunicacaoSefaz.consulta_distribuicao() got an unexpected keyword argument 'ultNSU'

**Comment by leogregianin** [comment]
@homerokzam se observar o método consulta_distribuicao aqui: 

https://github.com/TadaSoftware/PyNFe/blob/d1231c14aa2ff489ba76d4fb5e00ca8863ec1b48/pynfe/processamento/comunicacao.py#LL169C108-L169C108

Verá que não existe uma variável chamada `ultNSU` para ocorrer esse tipo de mensagem de erro.
Além disso, não entendi se está realizando a consulta por chave de acesso ou por último NSU.

Pode passar mais detalhes para resolver essa issue?

**Comment by juniortada** [comment]
Pela mensagem do erro me parece erro na utilização.
Vou encerrar por falta de informações.

**Comment by homerokzam** [comment]
Agora não deu erro. Estou tentando consulta pela última.

CHAVE = ''
ULT_NSU = 0

xml = con.consulta_distribuicao(cnpj=CNPJ, chave=CHAVE, nsu=ULT_NSU, consulta_nsu_especifico=False)
print(xml.text)

...
xMotivo>Rejeicao: Consumo Indevido (Deve ser utilizado o ultNSU nas solicitacoes subsequentes. Tente apos 1 hora)</xMotivo>
...


Como faço para consulta a emissão de uma NFe contra o CNPJ do certificado?

Obrigado.
