### ISSUE TITLE
Certificado para consultas de notas

### ISSUE THREAD

**Issue by Credmei** [TadaSoftware/PyNFe#274]
Vi os exemplos na documentação, e utiliza um arquivo de certificado e senha. Onde consigo esse certificado e a sua respectiva senha?

**Comment by Credmei** [comment]
```
from pynfe.processamento.comunicacao import ComunicacaoSefaz

certificado = "cte.fazenda.mg.gov.br.crt"
senha = ''
uf = 'mg'
homologacao = False

chave_acesso = '99999999999999999999999999999999999999999999'
con = ComunicacaoSefaz(uf, certificado, senha, homologacao)
envio = con.consulta_nota('nfe', chave_acesso) # nfe ou nfce
print (envio.text.encode('utf-8')) # SEFAZ SP utilizar envio.content
```

Minha dúvida é: esse arquivo de certificado, é esse mesmo que foi disponibilizado no site do Sefaz? (http://www.sped.fazenda.mg.gov.br/spedmg/cte/downloadsPasta/)
E a senha desse determinado arquivo, qual seria? Fiquei um pouco confuso com esse processo

**Comment by juniortada** [comment]
Boa noite @Credmei 
Não é esse certificado digital.
O certificado digital que é utilizando no PyNFe é aquele comprado comercialmente para o CNPJ/CPF
do emissor/usuário da biblioteca. É necessário tanto para assinar digitalmente documentos
como para assinar a comunicação com os webservices dos autorizadores das SEFAZ.
Exemplo:
https://loja.certisign.com.br/
https://safeweb.com.br/produtos/pjnfe

**Comment by Credmei** [comment]
Muito obrigado pela resposta
