### ISSUE TITLE
Atualização da dependência signxml

### ISSUE THREAD

**Issue by leogregianin** [TadaSoftware/PyNFe#278]
A partir da [versão 3.1.0 do signxml](https://github.com/XML-Security/signxml/releases) o algoritmo de criptografia SHA1 exigido pelos documentos fiscais (NFe, NFCe, MDFe, etc) para assinar os XMLs está obsoleto por padrão.

Para resolver deve-se sobrescrever o método `check_deprecated_methods`da classe `XMLSigner` para não [entrar no raise exception](https://xml-security.github.io/signxml/_modules/signxml/signer.html#XMLSigner.check_deprecated_methods).

**Comment by juniortada** [comment]
@leogregianin isso aqui resolve o problema?
https://github.com/TadaSoftware/PyNFe/pull/279

**Comment by juniortada** [comment]
https://github.com/TadaSoftware/PyNFe/pull/279
