### ISSUE TITLE
 Attribute Error: 'NoneType' object has no attribute '_x509' - Certificado corrompido como resolver?

### ISSUE THREAD

**Issue by SabrinaWinckler** [TadaSoftware/PyNFe#289]
Problema: Certificado digital corrompido - sem a chave privada.

Como pegar certificado NEOID sem ficar corrompido?

Baixei o .pfx incluindo a opção de com a chave privada, exportando ele a partir do google chrome mas nao funcionou... Alguém consegue me ajudar?

_Originally posted by @SabrinaWinckler in https://github.com/TadaSoftware/PyNFe/issues/102#issuecomment-1704393733_

**Comment by leogregianin** [comment]
@SabrinaWinckler conseguiu avançar sobre isso?
