### ISSUE TITLE
Dúvida sobre baixa NFC-e

### ISSUE THREAD

**Issue by HiagoCardos** [TadaSoftware/PyNFe#293]
Não estou muito habituado com o GitHub então não sei se deveria peguntar por aqui.
Mas lendo o projeto consegui usar a baixa de NF-e e a Consulta simples de NFe e NFC-e, só que eu precisava baixar NFC-e, como funciona no caso desse modelo de nota?
Alguém poderia me dar um auxilio, estou quebrando a cabeça e não consigo sair do mesmo ponto.

**Comment by leogregianin** [comment]
@HiagoCardos, não há nenhum webservice disponibilizado para baixar NFC-e, somente NF-e. Não é uma limitação desse projeto, simplesmente não existe a baixa.
