### ISSUE TITLE
<xMotivo>Rejeicao: Consumo Indevido (Ultrapassou o limite de 20 consultas por hora)</xMotivo>

### ISSUE THREAD

**Issue by HiagoCardos** [TadaSoftware/PyNFe#294]
Esse erro é devido a algo que estou fazendo de errado, ou por padrão a baixa de XML via Chave têm essa limitação mesmo?

**Comment by leogregianin** [comment]
@HiagoCardos essa é uma das regras do webservice.
Sugiro ler todos os manuais https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=ndIjl+iEFdE= e Notas técnicas https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=04BIflQt1aY= sobre NFe.
