### ISSUE TITLE
O tpEmis informado e incompativel

### ISSUE THREAD

**Issue by tonvecchi** [TadaSoftware/PyNFe#300]
Estou utilizando o código abaixo para tentar consultar uma NF-e
Ao utilizar ele, recebo o seguinte erro "O tpEmis informado e incompativel com a SVC-[AN/RS]522023-10-25T13:46:04-03:0052230932929819000477550010005115291435276844</soap:Body></soap:Envelope>'"

Mas o UF está correto nesse caso, que é SC. Como eu poderia ajustar isso?

from pynfe.processamento.comunicacao import ComunicacaoSefaz

certificado = "Certificado.pfx"
senha = '0000'
uf = 'sc'
homologacao = True

chave_acesso = '52230932929819000477550010005115291435276823'
con = ComunicacaoSefaz(uf, certificado, senha, homologacao)
envio = con.consulta_nota('nfe', chave_acesso) # nfe ou nfce
print (envio.text.encode('utf-8')) # SEFAZ SP utilizar envio.content

**Comment by juniortada** [comment]
@tonvecchi essa nota foi emitida em contingência?

**Comment by tonvecchi** [comment]
Não sei informar, mas tentei com outras Notas e o erro persiste.

**Comment by juniortada** [comment]
@tonvecchi você está consultando no ambiente errado. 
Essa chave de nota é de uma NF-e de produção.
Marque homologacao = False
