### ISSUE TITLE
Abandonar suporte a versões antigas do Python (3.6)

### ISSUE THREAD

**Issue by leotada** [TadaSoftware/PyNFe#302]
As versões 3.6 e 3.7 do Python já não são mais suportadas oficialmente pela PSF.
Recentemente as bibliotecas de criptografia que usamos deixaram de suportar a versão 3.6.
Devemos remover a badge (e testes) que indica suporte a esta versão, e possivelmente a 3.7 também.

**Comment by leogregianin** [comment]
Estou de acordo, não faz sentido manter versões não suportadas.
