### ISSUE TITLE
load_pkcs12 depreciado no OpenSSL.crypto

### ISSUE THREAD

**Issue by rafaelnoronha** [TadaSoftware/PyNFe#303]
Ao tentar consultar o serviço de NFe, me é retornado a exceção apontando que o método **load_pkcs12** foi depreciado de **OpenSSL.crypto**, já existe uma solução ou devo criar uma nova classe de certificado herdando de Certificado e implementar com os ajustes necessários?

**Comment by juniortada** [comment]
Seria isso?
https://github.com/TadaSoftware/PyNFe/pull/301

**Comment by juniortada** [comment]
Publicada nova versão:
https://github.com/TadaSoftware/PyNFe/pull/304
https://pypi.org/project/PyNFe/0.4.4/
