### ISSUE TITLE
NFSE - AttributeError: module 'collections' has no attribute 'MutableSequence'

### ISSUE THREAD

**Issue by BrunoAwdd** [TadaSoftware/PyNFe#307]
Estou tentando criar um app utilizando a NFSe, com o seguinte codigo

`
from pynfe.processamento.serializacao import SerializacaoNfse
from pynfe.processamento.assinatura import AssinaturaA1
from pynfe.processamento.comunicacao import ComunicacaoNfse
from pynfe.entidades.cliente import Cliente
from pynfe.entidades.emitente import Emitente
from pynfe.entidades.servico import Servico
from pynfe.entidades.notafiscal import NotaFiscalServico
from pynfe.utils.flags import CODIGO_BRASIL
from pynfe.utils import obter_codigo_por_municipio
import datetime
from decimal import Decimal

# prestador
emitente = Emitente(
    razao_social="NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL",
    nome_fantasia="Nome Fantasia da Empresa",
    cnpj="99999999000199",  # cnpj apenas números
    codigo_de_regime_tributario="1",  # 1 para simples nacional ou 3 para normal
    inscricao_estadual="9999999999",  # numero de IE da empresa
    inscricao_municipal="12345",
    cnae_fiscal="9999999",  # cnae apenas números
    endereco_logradouro="Rua da Paz",
    endereco_numero="666",
    endereco_bairro="Sossego",
    endereco_municipio="Paranavaí",
    endereco_uf="PR",
    endereco_cep="87704000",
    endereco_pais=CODIGO_BRASIL,
)

# tomador
cliente = Cliente(
    razao_social="NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL",
    tipo_documento="CNPJ",  # CPF ou CNPJ
    numero_documento="99999999999999",  # apenas os numero do CPF ou CNPJ
    inscricao_municipal="1234",  # opcional
    endereco_logradouro="Rua tal",
    endereco_numero="0",
    endereco_complemento="Ao lado de lugar nenhum",  # opcional
    endereco_bairro="Centro",
    endereco_cod_municipio="123",
    endereco_uf="PR",
    endereco_cep="87704000",
    endereco_pais=CODIGO_BRASIL,
    endereco_telefone="12365478945",  # opcional
    email="nome@email.com.br",  # opcional
)

# serviço
servico = Servico(
    valor_servico=Decimal("100.00"),
    iss_retido=1,  # 1 - Sim; 2 - Não
    item_lista="0101",
    discriminacao="Mensalidade",
    codigo_municipio=obter_codigo_por_municipio("Paranavaí", "PR"),
    # Dados opcionais
    codigo_cnae=6201501,
    codigo_tributacao_municipio="1234",
    valor_deducoes=Decimal("10.00"),
    valor_pis=Decimal("10.00"),
    valor_confins=Decimal("10.00"),
    valor_inss=Decimal("10.00"),
    valor_ir=Decimal("10.00"),
    valor_csll=Decimal("10.00"),
    valor_iss=Decimal("10.00"),
    valor_iss_retido=Decimal("10.00"),
    valor_liquido=Decimal("10.00"),
    outras_retencoes=Decimal("10.00"),
    base_calculo=Decimal("10.00"),
    aliquota=Decimal("10.00"),
    desconto_incondicionado=Decimal("10.00"),
    desconto_condicionado=Decimal("10.00"),
)

# nota
nota = NotaFiscalServico(
    identificador="50",
    data_emissao=datetime.datetime.now(),
    servico=servico,
    emitente=emitente,
    cliente=cliente,
    # Optante Simples Nacional
    simples=1,  # 1-Sim; 2-Não
    natureza_operacao=1,  # 1 – Tributação no município 2 - Tributação fora do município 3 - Isenção 4 - Imune
    # 5 –Exigibilidade suspensa por decisão judicial 6 – Exigibilidade suspensa por procedimento administrativo
    # regime_especial=1, # Regime Especial de Tributação: 1 – Microempresa municipal 2 - Estimativa
    # 3 – Sociedade de profissionais 4 – Cooperativa 5 - Microempresário Individual (MEI)
    # 6 - Microempresário e Empresa de Pequeno Porte (ME EPP)
    incentivo=2,  # Incentivador Cultural # 1-Sim; 2-Não
    serie="A1",
    tipo="1",
)

certificado = "/home/user/certificado.pfx"
senha = "senha"
homologacao = True

# serialização
serializador = SerializacaoNfse("ginfes")
xml = serializador.gerar_lote(nota)

# assinatura
a1 = AssinaturaA1(certificado, senha, "ginfes")
xml = a1.assinarLote(xml)

# envio
con = ComunicacaoNfse(certificado, senha, "ginfes", homologacao)
envio = con.enviar_lote(xml)

print(envio)
`

e estou tendo o retorno de erro:

`
Traceback (most recent call last):
  File "/usr/src/app/nfse.py", line 101, in <module>
    xml = serializador.gerar_lote(nota)
  File "/usr/local/lib/python3.10/site-packages/pynfe/processamento/serializacao.py", line 1969, in gerar_lote
    return SerializacaoGinfes().serializar_lote_assincrono(nfse)
  File "/usr/local/lib/python3.10/site-packages/pynfe/processamento/autorizador_nfse.py", line 259, in __init__
    _tipos = import_module("pynfe.utils.nfse.ginfes._tipos")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/pynfe/utils/nfse/ginfes/_tipos.py", line 10, in <module>
    import pyxb.binding
  File "/usr/local/lib/python3.10/site-packages/pyxb/binding/__init__.py", line 8, in <module>
    from . import datatypes
  File "/usr/local/lib/python3.10/site-packages/pyxb/binding/datatypes.py", line 1266, in <module>
    from . import content
  File "/usr/local/lib/python3.10/site-packages/pyxb/binding/content.py", line 807, in <module>
    class _PluralBinding (collections.MutableSequence):
AttributeError: module 'collections' has no attribute 'MutableSequence'
`

Alguem consegue me ajudar. Estou travado nesse ponto tem alguns dias.

**Comment by juniortada** [comment]
@BrunoAwdd o PyNFe está bem desatualizado para emissão de NFS-e.
Qual o município/autorizador? (Ginfes/Betha/etc?)
Provavelmente precisará implementar correções.
Aqui está sendo discutido uma nova implementação para emissão de NFS-e.
https://github.com/TadaSoftware/PyNFe/issues/305

**Comment by BrunoAwdd** [comment]
@juniortada eu corrigi fazendo um downgrade. Quando instalei o pyxb, ele foi para a versão 1.2.6, e deveria ser a 1.2.4;

Estou usando Ginfes
