### ISSUE TITLE
Dúvida certificado contador

### ISSUE THREAD

**Issue by HiagoCardos** [TadaSoftware/PyNFe#310]
Para usar o sistema de distribuição, a baixa de XML modelo 55, direto pelo certificado de contador, como é feito?
Tentei utilizar colocando CPF do contador ele dá erro no XML, quando eu coloco o CNPJ do cliente ele informa que o CPF informado é diferente das notas pesquisadas.
<xMotivo>Rejeicao: Falha no esquema xml</xMotivo> | esse é o erro ao usar o CPF do contador.

Estou usando o modelo errado, ou o PyNFe é exclusivo utilizando o certificado da própria empresa?

**Comment by juniortada** [comment]
@HiagoCardos a autorização para baixar xml's pelo contador varia entre as SEFAZ autorizadoras, mas basicamente você consulta como o emissor mas "envia" o certificado do contador. 
Precisa estar previamente autorizado, tem SEFAZ que tem essa função apenas via site ou em webservices que não pertencem ao padrão nacional.
Exemplo SEFAZ PR:
https://sped.fazenda.pr.gov.br/NFe/Pagina/Servico-de-Download-de-NF-e
O que eu recomendo é no momento da emissão, adicionar o cnpj/cpf do certificado que deseja baixar essa nota na tag autXML.
Dessa forma independe de regras customizadas de SEFAZ autorizadoras. Basta consultar como o CNPJ emissor mas utilizando o certificado do CNPJ/CPF declarado no autXML.
Código que preenche esta tag:
https://github.com/TadaSoftware/PyNFe/blob/main/pynfe/processamento/serializacao.py#L267-L284
