### ISSUE TITLE
ajuda

### ISSUE THREAD

**Issue by GsChaves1** [TadaSoftware/PyNFe#320]
Oi, acabei de ver que existe essa API e eu estou desenvolvendo uma automacao que consulta a nota pela chave de acesso e joga em uma planilha, porem nao encontrei documentacao sobre isso, preciso de ajuda para pegar apenas, numero da nota, data de emissao, volume,valor e etc, vc consegue me dar uma luz de como faco essa requisicao?

**Comment by GsChaves1** [comment]
from pynfe.processamento.comunicacao import ComunicacaoSefaz

certificado = "xxxx"
senha = 'xxxx'
uf = 'MG'
homologacao = True

chave_acesso = 'XXXXXX'
con = ComunicacaoSefaz(uf, certificado, senha, homologacao)
envio = con.consulta_nota('nfe', chave_acesso)  # nfe ou nfce
print(envio.text.encode('utf-8'))  # SEFAZ SP utilizar envio.content




a documentacao mais proxima que encontrei foi essa porem eu procuro a consulta no site "https://www.nfe.fazenda.gov.br/"
se alguem conseguir me ajudar...

**Comment by juniortada** [comment]
@GsChaves1 essa consulta é apenas para saber o status da nota (autorização de uso).
Para extrair dados da nota você precisa extrair diretamente do xml.
