### ISSUE TITLE
Qual endpoint eu pego a listagem das notas para manifestação de interesse? 

### ISSUE THREAD

**Issue by talesmm14** [TadaSoftware/PyNFe#321]
Vi que tem o endpoint para [manifestar interesse](https://github.com/TadaSoftware/PyNFe/wiki/Manifesta%C3%A7%C3%A3o-Destinat%C3%A1rio) nas notas, quando já tenho a chave de acesso. No site da [fazenda](https://www.nfe.fazenda.gov.br/portal/manifestacaoDestinatario.aspx) consigo visualizar todas as notas manifestadas no CNPJ apenas com o certificado e CNPJ sem precisar de outro campo.

**Comment by felps-dev** [comment]
Tem um equívoco do que é o que, Manifestar é você dizer a SEFAZ que você reconhece aquela nota.
O site da Fazenda você faz 2 coisas:
1. Consulta distribuição
2. Realiza manifestação (Ciência da operação por ex)

O que você quer: https://github.com/TadaSoftware/PyNFe/wiki/Consulta-Distribui%C3%A7%C3%A3o
