### ISSUE TITLE
Nâo consigo Consultar Notas

### ISSUE THREAD

**Issue by Rooseveltterceiro** [TadaSoftware/PyNFe#325]
Estou tentando consultar as notas de um determinado período do mês (Ex: de 1 a 15 de fevereiro) com um certificado digital e até o momento está sempre apresentando a seguinte "", line 1, in <module>
    from pyxb import BIND
ModuleNotFoundError: No module named 'pyxb'"

from pynfe.processamento.serializacao import SerializacaoNfse
from pynfe.processamento.comunicacao import ComunicacaoNfse
from pynfe.processamento.assinatura import AssinaturaA1
from pynfe.entidades.emitente import Emitente

certificado = "certificados/XXXX.pfx"
senha = 'XXXX'

emitente = Emitente(
    cnpj='XXXXX'
    )

start_date = '2024-02-01'
end_date = '2024-02-15'

serializador = SerializacaoNfse(autorizador="ginfes")
nfse = serializador.consultar_nfse(emitente, inicio=start_date, fim=end_date)

a1 = AssinaturaA1(certificado, senha)
xml = a1.assinarConsulta(nfse, retorna_string=True)

con = ComunicacaoNfse(certificado, senha)
retorno = con.consultar(xml)
print(retorno.text)

**Comment by rdelazzeri** [comment]
Olá, acabo de ter um problema semelhante. 
No meu caso, eu havia atualizado a versão da biblioteca pyOpenSSL para versão 24.0.0 e esta versão está incompatível com o pyNFe pois não possui mais essa biblioteca: OpenSSL.crypto.PKCS12 necessária na importação do certificado A1. Como forma paliativa, fiz um downgrade da pyOpenSSl para a versão 23.2.0 e voltou a funcionar.
https://github.com/pyca/pyopenssl/blob/main/CHANGELOG.rst#2330-2023-10-25

**Comment by felps-dev** [comment]
Eu já resolvi isso na versão que está na master, a do pypi está em Outubro de 2023.
