### ISSUE TITLE
Rejeição 486 (Sefaz Bahia) - Implementar o grupo de Tags autXML 

### ISSUE THREAD

**Issue by asjsandro** [TadaSoftware/PyNFe#333]
03.8 Autoriza Acesso ao XML#
Atualmente na Consulta Pública da NF-e tanto o destinatário, quanto o próprio emitente, podem efetuar o download do XML da NF-e, desde que identificados 
com seu certificado digital (conforme critério da SEFAZ). Idem para o Transportador citado na NF-e.
Criado um novo grupo de informações para que a empresa emitente possa indicar outras pessoas autorizadas a ter acesso ao arquivo XML da NF-e. Nesta 
alternativa, a empresa emitente poderá indicar o seu Contador, outras pessoas envolvidas no transporte da mercadoria, etc.

![image](https://github.com/TadaSoftware/PyNFe/assets/23367306/d54b5b9d-bf2c-45ea-acfb-67051541e31d)
exemplo:

```
<autXML>
    <CNPJ>99999999999999</CNPJ>
</autXML>
```

**Comment by juniortada** [comment]
@asjsandro existe autXML no PyNFe:
https://github.com/TadaSoftware/PyNFe/blob/main/pynfe/processamento/serializacao.py#L268

Exemplo na wiki
https://github.com/TadaSoftware/PyNFe/wiki/Emiss%C3%A3o-de-NFe#:~:text=%23%20exemplo%20de%20grupo%20de%20pessoas%20autorizadas%20a%20baixar%20xml%0A%23%20autxml_lista%20%3D%20%5B%2799999999000199%27%2C%20%2700000000040%27%5D%0A%23%20for%20index%2C%20item%20in%20enumerate(autxml_lista%2C%201)%3A%0A%23%20%20%20%20nota_fiscal.adicionar_autorizados_baixar_xml(CPFCNPJ%3Ditem)
