### ISSUE TITLE
Eventos não retornados em consultas para uf de SP

### ISSUE THREAD

**Issue by ruanssh** [TadaSoftware/PyNFe#338]
Estou desenvolvendo uma aplicação pra consultar eventos da nota fiscal, porém quanto vou consultas de são paulo não traz os eventos, quando traz não traz todos.

Ja testei para outras uf e traz os eventos das minhas notas normais, porém quando é SP não retorna os evento

**"procEventoNFe" é o que não vem no xml, quando vem não vem com todos**

```
from pynfe.processamento.comunicacao import ComunicacaoSefaz
import xml.etree.ElementTree as ET

def consulta_nota(chave):
    certificado = ""
    senha = ''
    uf = 'sp'  
    homologacao = False

    con = ComunicacaoSefaz(uf, certificado, senha, homologacao)
    
    envio = con.consulta_nota('nfe', str(chave))
    
    xml_response = ET.fromstring(envio.content)
    
    return xml_response

def salvar_xml(xml_elemento, caminho_arquivo):
    xml_string = ET.tostring(xml_elemento, encoding='utf-8').decode('utf-8')

    with open(caminho_arquivo, 'w', encoding='utf-8') as arquivo:
        arquivo.write(xml_string)

chave = ''

xml_result = consulta_nota(chave)

salvar_xml(xml_result, 'consulta_nota.xml')

```

**Comment by leogregianin** [comment]
@ruanssh me parece mais um problema do webservice de São Paulo que um problema dessa biblioteca.

**Comment by ruanssh** [comment]
sim, testei a usando a propia webservice de SP e não retorna os eventos.. fechando a issue aqui.
