### ISSUE TITLE
Manifestação Destinatário - Rejeicao: Código do Orgao diverge do orgao autorizador

### ISSUE THREAD

**Issue by CopyEFSystem** [TadaSoftware/PyNFe#344]
### Estou tentando usar o evento de "Confirmar Operação"

    uf = 'ba'

    manif_dest = EventoManifestacaoDest(
        cnpj=cnpj,  # cnpj do destinatário
        chave=chave, # chave de acesso da nota
        data_emissao=datetime.datetime.now(),
        uf=uf,
        operacao=operacao  # - numero da operacao
        )

    # serialização
    serializador = SerializacaoXML(_fonte_dados, homologacao=homologacao)
    nfe_manif = serializador.serializar_evento(manif_dest)

    # assinatura
    a1 = AssinaturaA1(certificado, senha)
    xml = a1.assinar(nfe_manif)

    con = ComunicacaoSefaz(uf, certificado, senha, homologacao)
    envio = con.evento(modelo='nfe', evento=xml)  # modelo='nfce' ou 'nfe'

    print(envio.text)

más estou obtendo esse retorno:
```
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><nfeRecepcaoEventoNFResult xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4"><retEnvEvento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>1</idLote><tpAmb>1</tpAmb><verAplic>AN_1.8.2</verAplic><cOrgao>91</cOrgao><cStat>128</cStat><xMotivo>Lote de evento processado</xMotivo><retEvento versao="1.00"><infEvento><tpAmb>1</tpAmb><verAplic>AN_1.8.2</verAplic><cOrgao>91</cOrgao><cStat>657</cStat><xMotivo>Rejeicao: Código do Orgao diverge do orgao autorizador</xMotivo><chNFe>35240553612099000149550000001405201158721445</chNFe><tpEvento>210200</tpEvento><xEvento>Confirmacao da Operacao</xEvento><nSeqEvento>1</nSeqEvento><dhRegEvento>2024-06-18T09:08:50-03:00</dhRegEvento></infEvento></retEvento></retEnvEvento></nfeRecepcaoEventoNFResult></soap:Body></soap:Envelope>
```
Erro ao tentar mudar status da operação na Data Base: Nenhum resultado retornado(Erro de banco de dados)

### Minha dúvida é se o uf a ser informado deverá ser o uf de autorização da nota enviada pelo fornecedor(Nota a ser manifestada)

Desde já agradeço pela ajuda a entender esse problema. 🙏

@leogregianin @juniortada

**Comment by leogregianin** [comment]
@CopyEFSystem, a uf é do ambiente nacional. Aqui tem um exemplo: https://github.com/TadaSoftware/PyNFe/wiki/Manifesta%C3%A7%C3%A3o-Destinat%C3%A1rio
