### ISSUE TITLE
Varias formas de pagamento

### ISSUE THREAD

**Issue by joselobinho** [TadaSoftware/PyNFe#35]
Ola amigos tem como adicionar varias formas de pagamento

**Comment by juniortada** [comment]
????

**Comment by victorpb** [comment]
@joselobinho  você está falando das mudanças do detalhamento do pagamaento da nf-e 4.0?

Detalha ai melhor o que você quer dizer.

**Comment by joselobinho** [comment]
OK, detalho sim
como faco para passar essas alteracoes
To fazendo alteracoes para desconto no item, frete, acrescimo

**Comment by juniortada** [comment]
Exemplo desconto, frete e acrescimo:

# Produto
nota_fiscal.adicionar_produto_servico(
    codigo='000328',                           # id do produto
    descricao='NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL',
    ncm='99999999',
    #cest='0100100',                            # NT2015/003
    cfop='5102',
    unidade_comercial='UN',
    quantidade_comercial=Decimal('12'),        # 12 unidades
    valor_unitario_comercial=Decimal('9.75'),  # preço unitário
    valor_total_bruto=Decimal('117.00'),       # preço total
    unidade_tributavel='UN',
    quantidade_tributavel=Decimal('12'),
    valor_unitario_tributavel=Decimal('9.75'),
    ind_total=1,
    # numero_pedido='12345',                   # xPed
    # numero_item='123456',                     # nItemPed
    icms_modalidade='102',
    icms_origem=0,
    icms_csosn='400',
    pis_modalidade='07',
    cofins_modalidade='07',
    valor_tributos_aprox='21.06',
    **total_frete=Decimal('10.99'),**           # frete
    **desconto=Decimal('1.99'),**              # Desconto
    **outras_despesas_acessorias=Decimal('8.99')** # Outros
    )

No xml esses valores serão somados e adicionados e serializados nas tags <vFrete>, <vDesc> e <vOutro> nas informações da tag <total> da NF-e.


https://github.com/TadaSoftware/PyNFe/blob/master/pynfe/processamento/serializacao.py#L531
