### ISSUE TITLE
Emitir NFCe sem dados do cliente

### ISSUE THREAD

**Issue by batistaluccas** [TadaSoftware/PyNFe#366]
Como devo enviar os dados para a web service quando não preciso informar os dados do cliente?

**Comment by batistaluccas** [comment]
Posso omitir a classe cliente?

**Comment by leogregianin** [comment]
@batistaluccas isso mesmo. Consulta aqui mais detalhes: https://github.com/TadaSoftware/PyNFe/discussions/150
