### ISSUE TITLE
Emitir NF apenas com .cer

### ISSUE THREAD

**Issue by gmonnerat** [TadaSoftware/PyNFe#40]
A contadora me enviou apenas o arquivo .cer e se entendi corretamente, esse arquivo é apenas a chave pública.

Eu consigo emitir notas com esse arquivo?

Tentei utilizá-lo mas obviamente ocorre um erro com ssl.

Nesse mesmo certificado, eu consigo gerar o pfx?

Desde já agradeço

**Comment by juniortada** [comment]
Bom dia Gabriel!
No PyNFe só é possível emitir notas com o certificado do tipo A1 no formato .pfx
Se o seu certificado .cer estiver completo, você pode conseguir "converter" ele para o formato .pfx
Importe o certificado .cer no navegador de internet e procure a opção exportar para o formato .pfx
Mas nem sempre isto é possível pois o certificado .cer muitas vezes contêm apenas a chave publica.
Neste caso você precisa pedir o certificado no formato .pfx ou comprar um novo certificado digital do tipo A1 no formato .pfx

**Comment by gmonnerat** [comment]
Bom dia Junior!!

Obrigado pelo feedback. Acredito que o certificado A1 contêm apenas a chave publica.

Testei o memo [código](https://github.com/TadaSoftware/PyNFe/wiki/Consulta-status-do-servi%C3%A7o) com outro certificado mas em .pfx e funcionou sem problemas!
