### ISSUE TITLE
Dados CTe

### ISSUE THREAD

**Issue by viniciuspiloto** [TadaSoftware/PyNFe#52]
Olá, estou estudando a integração dos webservices do SEFAZ e Python, só que quero trazer os dados do CTe, imagino que o processo seja praticamente o mesmo, correto?

**Comment by juniortada** [comment]
Sim, CTe é muito parecido com NFe. Infelizmente o PyNFe ainda não trabalha com CTe nem MDFe.
Acredito que você irá precisar de ambos, dependendo do caso.
Tem um branch para desenvolver MDFe mas está a algum tempo sem desenvolvimento.
