### ISSUE TITLE
Erro ao gerar NF-e São Paulo

### ISSUE THREAD

**Issue by luizsfer** [TadaSoftware/PyNFe#57]
Olá, tudo bem?
Quando tento emitir uma nota para SP tenho a mensagem de erro, porém a mesma informa "Lote recebido com sucesso".
Quando tento validar do SEFAZ - RS tenho alguns erros informado:

- Assinatura Digital: Inválida
- Regras de Negócio [Ambiente de Homologação (Testes)]
      - 587 - [Simulacao] Rejeicao: Usar somente o namespace padrao da NF-e
      - 245 - [Simulacao] Rejeicao: CNPJ Emitente nao cadastrado

**Comment by juniortada** [comment]
Bom dia Luiz!
É NF-e ou NFC-e?
Sua nota foi enviada (lote) para a SEFAZ, porém ela não foi autorizada.
Pela mensagem do erro é por problema na assinatura do xml. 
Quando seu xml estiver passando no validador da SEFAZ - RS envie a nota, aguarde algum tempo e depois consulte a nota pela chave para saber se foi autorizada.
