### ISSUE TITLE
Dúvida - Assinatura é funcional para XML de MDF-e?

### ISSUE THREAD

**Issue by linneudm** [TadaSoftware/PyNFe#61]
Olá galera, boa tarde!
Estou tentando implementar algumas funções para envio de lote de Manifesto Eletrônico e gostaria de saber se alguém conseguiu assinar um XML utilizando a mesma biblioteca que é disponibilizada aqui no PyNFe.

**Comment by juniortada** [comment]
A assinatura digital é igual para qualquer documento. A lib que utilizamos é singxml.
Existe um fork para MDF-e mas não está com desenvolvimento ativo.
https://github.com/TadaSoftware/PyNFe/tree/mdfe

**Comment by linneudm** [comment]
Tudo bem. Estou vendo aqui qual o problema. Na documentação não consta que para consultar o retorno do envio do MDF-e precisa de assinatura, mas quando tento validar o xml diretamente no site, ele diz que a mensagem não está assinada. o.O
