### ISSUE TITLE
Urls faltantes para MG

### ISSUE THREAD

**Issue by mateusfilipeteixeira** [TadaSoftware/PyNFe#69]
Boa tarde pessoal!
Tudo tranquilo?

Vamos utilizar a aplicação para emissão de nfce em mg, porém vi que como a nfce é nova em Minas, o sistema ainda não tem as urls para comunicação

**Comment by juniortada** [comment]
Adicionado!
http://www.sped.fazenda.mg.gov.br/spedmg/nfce/web-services/

**Comment by mateusfilipeteixeira** [comment]
Obrigado!
