### ISSUE TITLE
Nao consigo ver o conteudo da nota

### ISSUE THREAD

**Issue by dario13** [TadaSoftware/PyNFe#71]
Boa tarde! Quando faço a consulta da nota fiscal, o xml de resposta contem a seguinte mensagem: 

<cStat>100</cStat><xMotivo>Autorizado o uso da NF-e</xMotivo>

Pelo que pesquisei o código é de confirmação, pelo que a consulta está bem feita, mas não consigo entender como faço para ver o conteúdo da nota fiscal, tentei com envio.text e envio.content mas a mensagem é a mesma. 

Agradeço pela ajuda.

**Comment by juniortada** [comment]
Boa tarde Dario, não é possível ver o conteúdo da NF-e com a consulta, apenas o status (se foi emitida/cancelada/etc).
O método consultar nota retorna apenas um xml de resposta da SEFAZ, de acordo com a documentação do modelo nacional.
Se você foi o emissor desta nota, então possui o xml de envio, se for o destinatário ou ainda transportador da mercadoria, é possível fazer o download de lotes de NF em determinados intervalos de tempo (dependendo da SEFAZ/UF), mediante manifestação do destinatário e consulta distribuição.

https://github.com/TadaSoftware/PyNFe/wiki/Manifesta%C3%A7%C3%A3o-Destinat%C3%A1rio
https://github.com/TadaSoftware/PyNFe/wiki/Consulta-Distribui%C3%A7%C3%A3o

**Comment by dario13** [comment]
Muito obrigado pela rápida resposta! 
Então, não posso descargar as notas fiscais do emissor fazendo uma chamada desde a biblioteca? que nem quando faço manualmente no site da sefaz: https://www.sefaz.rs.gov.br/nfe_cert/NFE-CER-CON.aspx  ou vendo a nota mesma entrando mediante QR code ou com chave de acceso no site da fazenda.
Meu caso sei que pode parecer estranho, mas é porque eu peço o certificado digital para uma loja e quando um cliente da loja faz a leitura do QR da nota fiscal emitida por essa loja, eu preciso validar que essa compra pertence a essa loja e ver o valor da mesma, para dar um beneficio a esse cliente. Conseguia fazer esta validação direta fazendo scraping na URL do QR code no site da fazenda, mas o serviço não está funcionando e é muito instável. Espero ter sido claro.

**Comment by juniortada** [comment]
Só é possível por scraping mesmo, nem todas as UF's tem esse serviço, alguns que tinham estão desativando. Não tem relação com os webservices de emissão/cancelamento/etc.
Mas como você tem acesso ao certificado digital e não tem acesso aos xml's?
Qual a UF? Qual o sistema fiscal (emissor de nota) dessa loja? Alguns sistemas ERP ou emissores tem API para consulta interna.

**Comment by dario13** [comment]
Entendo, uma pena isso de que estejam desativando esse serviço pelo QR. 
Tenho acceso ao certificado digital porque as lojas são nossas parceiras, a questão é que não queria colocar algum tipo de lógica do lado do lojista e controlar todas as notas centralizadamente desde meu servidor, mas pelo visto dessa forma não vai ser possível. 
A UF é RJ. O sistema destas primeras lojas é o colibri, acho que o que vou fazer é montar um ftp na pasta dos xmls emitidos e mandar isso para meu servidor. 
Agradeço muito pela ajuda e o interesse.
