### ISSUE TITLE
Teste inicial do status do servico

### ISSUE THREAD

**Issue by edilmar** [TadaSoftware/PyNFe#72]
Ola,

Ao rodar o test.py, eu alterei para nao autorizar, apenas para chamar o
metodo do status do servico de varias UFs. Todas dao o erro:

requests.exceptions.SSLError: HTTPSConnectionPool(host='homolog.sefaz.go.gov.br', port=443): Max retries exceeded with url: /nfe/services/NFeStatusServico4?wsdl (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))

Por ex. acima o erro é da SEFAZ/GO.

Usei o mesmo certificado que tenho em uma aplicacao Java que autoriza NFe/CTe/MDFe
em varios estados sem problemas.

**Comment by juniortada** [comment]
Boa tarde Edilmar!

Siga a documentação da Wiki para fazer testes/desenvolver aplicações com PyNFe
https://github.com/TadaSoftware/PyNFe/wiki

Consulta Status:
https://github.com/TadaSoftware/PyNFe/wiki/Consulta-status-do-servi%C3%A7o

Testei várias UFs e estão todas operantes.
Seu erro me parece erro no certificado (ou como vc gerou/exportou ele),
ou erro de ssl/tls do sistema operacional/python, etc.

Para poder te ajudar precisaria de mais informações como tipo de nota(NFe ou NFCe), UF,
versão do python, sistema operacional, versão do sistema operacional.
