### ISSUE TITLE
Tutorial de como importar o projeto no PyCharm

### ISSUE THREAD

**Issue by edilmar** [TadaSoftware/PyNFe#73]
Eu consegui abrir via git no PyCharm, mas como um projeto separado.
Como eu faria para localizar o projeto via File - Settings - Project Interpreter,
para importar a biblioteca diretamente no meu projeto?

**Comment by leotada** [comment]
Acredito que não tem como adicionar diretamente pelo PyCharm, você teria que adicionar pelo terminal mesmo usando o pip.
