### ISSUE TITLE
Erro na serialização da alíquota do PIS no Produto

### ISSUE THREAD

**Issue by leogregianin** [TadaSoftware/PyNFe#81]
O percentual da alíquota do PIS está sem o format e ocorre erro na serialização do XML. `'{:.2f}'.format(produto_servico.pis_aliquota_percentual or 0)`

https://github.com/TadaSoftware/PyNFe/blob/249d6183a552ee7d64f203c682038ff075e084d2/pynfe/processamento/serializacao.py#L374

https://github.com/TadaSoftware/PyNFe/blob/249d6183a552ee7d64f203c682038ff075e084d2/pynfe/processamento/serializacao.py#L383

**Comment by leotada** [comment]
Feito. Obrigado.
