### ISSUE TITLE
Dúvida sobre envio de NFC-e com mais de uma forma de pagamento

### ISSUE THREAD

**Issue by hugohomesquita** [TadaSoftware/PyNFe#83]
Olá, olhei um pouco o código e aparentemente não permite informar mais de uma forma de pagamento na NFC-e, estou correto?

Ex:
100,00 Cartão de crédito
50,00 Dinheiro
30,00 Cartão de débito

**Comment by juniortada** [comment]
Correto Hugo, esta funcionalidade ainda não foi implementada.

**Comment by hugohomesquita** [comment]
Blz! Vou fazer um fork e implementar.
