### ISSUE TITLE
Distribuição e Status da CTe

### ISSUE THREAD

**Issue by tiagocardosos** [TadaSoftware/PyNFe#88]
Caros, seria pertinente ao projeto a inclusão dos serviços de Distribuição e Status da CTe?

**Comment by leogregianin** [comment]
> Caros, seria pertinente ao projeto a inclusão dos serviços de Distribuição e Status da CTe?

Bom dia @tiagocardosos, está nos meus planos implementar todos os webservices relacionados ao CTe, da mesma forma que fiz com o MDFe [nesse PR](https://github.com/TadaSoftware/PyNFe/pull/79), não tenho certeza se entraria nesse projeto ou seria um projeto a parte.

**Comment by leogregianin** [comment]
Deixar aqui algumas referências para implementação do CT-e:
* [Manuais](https://www.cte.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=YIi+H8VETH0=)
* [Schemas](https://www.cte.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=0xlG1bdBass=)
* [Relação de Webservices](https://www.cte.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=wpdBtfbTMrw=)

**Comment by ibemoreira** [comment]
@tiagocardosos  Estou tentando fazer a distribuição de Ct-e o @leogregianin  Me deu o caminho das pedras, estou a semanas quebrando cabeça com isso, deixo meu convite se quiser colaborar, quem sabe duas cabeças pensando kkkk

**Comment by tiagocardosos** [comment]
@ibemoreira conseguiu evoluir? Posso te ajudar, caso ainda seja necessário.

**Comment by ibemoreira** [comment]
> @ibemoreira conseguiu evoluir? Posso te ajudar, caso ainda seja necessário.

@tiagocardosos  Consegui sim esta rodando já, muitoo obrigado brother!
