### ISSUE TITLE
Separação dos grupos de CST de ICMS

### ISSUE THREAD

**Issue by leogregianin** [TadaSoftware/PyNFe#91]
Bom dia, 
A serialização das informações de cada CST de ICMS no PyNFe está confusa e faltando diversos campos e grupos de CST ([link](https://github.com/TadaSoftware/PyNFe/blob/3a72289077ba72d27c3763c559bcdfa30e5eb13a/pynfe/processamento/serializacao.py#L281)).

@leotada e @juniortada o que acham de separarmos e deixar mais explícito os campos de cada CST de ICMS como o Projeto ACBr faz [aqui](https://github.com/frones/ACBr/blob/0cedf86947d8d3e81d71928ff5172b33064199ac/Fontes/ACBrDFe/ACBrNFe/PCNNFe/pcnNFeW.pas#L1376)?

**Comment by juniortada** [comment]
Alterado a serialização dos impostos.
