### ISSUE TITLE
SEFAZ BA - Erro ao gerar nota

### ISSUE THREAD

**Issue by PedroPCardoso** [TadaSoftware/PyNFe#93]
Estou tentando emitir notas na uf=BA

A nota é enviada mas sai impresso na nfe
SEM VALOR FISCALFALTA PROTOCOLO DE APROVAÇÃO DA SEFAZ

Ao consultar via protocolo a seguinte informação é dada : 

Não informado o Grupo de Autorização para UF que exige a identificação do Escritório de Contabilidade na Nota Fiscal - Caso não possua informar o CNPJ da SEFAZ Bahia 13.937.073/0001-56 

Sendo que já adicionei

# responsável técnico | Dados do contador   
        nota_fiscal.adicionar_responsavel_tecnico(
            cnpj='13937073000156',
            contato='SEFAZ',
            email='faleconosco@sefaz.ba.gov.br',
            fone='11912341234'
        )

**Comment by leogregianin** [comment]
Boa tarde @PedroPCardoso,

Essa rejeição da SEFAZ-BA não se refere ao grupo "Responsável Técnico" e sim as pessoas autorizadas a baixar o XML. Veja mais detalhes [aqui](https://atendimento.tecnospeed.com.br/hc/pt-br/articles/360018393493-Rejei%C3%A7%C3%A3o-486-N%C3%A3o-informado-o-Grupo-de-Autoriza%C3%A7%C3%A3o-para-UF-que-exige-a-identifica%C3%A7%C3%A3o-do-Escrit%C3%B3rio-de-Contabilidade-na-Nota-Fiscal)

Esse grupo AutXML está implementado [nesse PR](https://github.com/TadaSoftware/PyNFe/pull/90). Você precisa informar o CNPJ da Contabilidade ou da SEFAZ-BA.

**Comment by PedroPCardoso** [comment]
Putz, preciso desse pull! kkk

Kd essa galera para aprovar ?

**Comment by leotada** [comment]
PR #90 merged.
