### ISSUE TITLE
Adicionar testes unitários

### ISSUE THREAD

**Issue by leotada** [TadaSoftware/PyNFe#94]
Adicionar estrutura de testes unitários.

**Comment by leogregianin** [comment]
> Adicionar estrutura de testes unitários.

A ideia é aproveita a mesma estrutura de testes de que já existe em ```/tests``` com o ```run_tests.py``` e ```run_fake_soap_server.py``` ou criar uma nova?

**Comment by leotada** [comment]
Acho que essas estruturas nunca foram utilizadas. Podemos criar uma nova.

**Comment by juniortada** [comment]
Adicionado pelo @leogregianin
