### ISSUE TITLE
Nota Fiscal de Remessa

### ISSUE THREAD

**Issue by diegohutter** [TadaSoftware/PyNFe#96]
Boa tarde.
Gostaria de saber se existe algum lugar que indique que a nota é uma nota de remessa ou se, na verdade, isso é informado de acordo com a natureza da operação.

Obrigado!

**Comment by juniortada** [comment]
Boa tarde @diegohutter!
Sim, remessa é informado de acordo com a natureza da operação.
Remessa (existem vários tipos, como por exemplo demonstração, industrialização, etc) você informa na natureza da operação, além de usar CFOP próprio para isso.
Dependendo do caso também precisa alterar finalidade de emissão (remessa de devolução)
e nota fiscal referenciada (chave da nfe gerador do fato).

**Comment by diegohutter** [comment]
Obrigado pela resposta, @juniortada!

Excelente!
